package sources

import (
	"path/filepath"
	"regexp"
	"strings"
)

// chatFolderName is the name WorkBuddy gives the folder it opens for each new
// chat under its workspace root: ~/WorkBuddy AI/2026-10-05-15-06-37. The app
// itself tells these apart from folders a user picked by this last segment
// alone (isAutoGeneratedWorkspace in its conversations module), since the root
// is named after the app, its edition and instance, or a path set in settings.
var chatFolderName = regexp.MustCompile(`^\d{4}-\d{2}-\d{2}-\d{2}-\d{2}-\d{2}$`)

// ChatWorkspaceRoot is the workspace root a per-chat folder sits in, so every
// chat under it is one project rather than one project each (#4735). ok is
// false for any other directory.
func ChatWorkspaceRoot(cwd string) (string, bool) {
	clean := strings.TrimRight(cwd, `/\`)
	if !chatFolderName.MatchString(filepath.Base(clean)) {
		return "", false
	}
	root := filepath.Dir(clean)
	if root == "." || root == clean || filepath.Dir(root) == root {
		return "", false
	}
	return root, true
}

// dropChatFolder is segs without a trailing per-chat folder.
func dropChatFolder(segs []string) []string {
	if n := len(segs); n >= 2 && chatFolderName.MatchString(segs[n-1]) && !isDriveSegment(segs[n-2]) {
		return segs[:n-1]
	}
	return segs
}
