package main

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/vshulcz/deja-vu/internal/sources"
)

// Hermes takes plugins as a directory under ~/.hermes/plugins with a
// plugin.yaml manifest and an __init__.py exporting register(ctx). Of its
// hooks only pre_llm_call can inject: whatever it returns under "context" is
// appended to the user message, which is also where Hermes wants it — the
// system prompt stays byte-identical so provider caching survives.
func installHermesPlugin(exe string, uninstall bool) (installResult, error) {
	// The launcher, not this binary: a generated plugin is as much a
	// config as a hooks.json, and one that names the build it was
	// installed from stops working the day that build moves (#3682).
	exe = hookExeFor(exe, uninstall)
	dir := filepath.Join(sources.HermesHome(), "plugins", "deja")
	if uninstall {
		if _, err := os.Stat(dir); err != nil {
			return installResult{Path: dir, Action: "unchanged"}, nil
		}
		if err := os.RemoveAll(dir); err != nil {
			return installResult{}, err
		}
		// And the directories deja made above it, while each is empty and
		// the record says it is deja's (#3698).
		pruneCreatedDir(filepath.Dir(dir))
		if err := setHermesPluginEnabled(false); err != nil {
			return installResult{}, err
		}
		return installResult{Path: dir, Action: "removed"}, nil
	}
	noteCreatedDirs(dir)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return installResult{}, err
	}
	manifestPath := filepath.Join(dir, "plugin.yaml")
	oldManifest, err := readConfig(manifestPath)
	if err != nil {
		return installResult{}, err
	}
	if _, err := writeIfChanged(manifestPath, oldManifest, []byte(hermesPluginManifest)); err != nil {
		return installResult{}, err
	}
	codePath := filepath.Join(dir, "__init__.py")
	oldCode, err := readConfig(codePath)
	if err != nil {
		return installResult{}, err
	}
	a, err := writeIfChanged(codePath, oldCode, []byte(hermesPluginPy(exe)))
	if err != nil {
		return installResult{}, err
	}
	// A discovered plugin is listed as "not enabled" and never loaded until
	// its name is in plugins.enabled, so the installer puts it there rather
	// than leaving the user a second step nothing tells them about.
	if err := setHermesPluginEnabled(true); err != nil {
		return installResult{}, err
	}
	return installResult{Path: dir, Action: a}, nil
}

const hermesPluginManifest = `name: deja
version: 0.1.0
description: Recall your own past coding sessions before answering
provides_hooks:
  - pre_llm_call
provides_commands:
  - deja
`

func hermesPluginPy(exe string) string {
	return fmt.Sprintf(`"""Generated by deja install — safe to delete; regenerate with: deja install hermes-auto."""

import json
import os
import subprocess

DEJA = %s


def _deja(args, payload="", timeout=10):
    """Never let memory break a turn: a failure here returns nothing."""
    try:
        done = subprocess.run(
            [DEJA, *args],
            input=payload,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        return done.stdout.strip()
    except Exception:
        return ""


def _provider_active():
    """True when deja is the configured memory provider (memory.provider in
    config.yaml): the provider then injects the same recall before each turn,
    and a hook that repeats it would hand the model everything twice."""
    try:
        from hermes_cli.config import cfg_get, load_config
        if cfg_get(load_config(), "memory", "provider") != "deja-memory":
            return False
        # Config can outlive the provider (an uninstall, a deleted directory),
        # and a provider that is there can still fail to load on a Hermes build
        # it was not written for — the hook then stood down for a provider that
        # was answering nothing (#3390). Ask the loader, and fall back to the
        # file when this build has no loader to ask.
        here = os.path.dirname(os.path.abspath(__file__))
        present = os.path.isfile(os.path.join(os.path.dirname(here), "deja-memory", "__init__.py"))
        if not present:
            return False
        try:
            from plugins.memory import load_memory_provider
        except Exception:
            # No loader to ask on this build: load the provider the way Hermes
            # would. A directory that raises on import is not a provider, and
            # the hook has to keep answering (#3340).
            try:
                import importlib.util
                spec = importlib.util.spec_from_file_location(
                    "_deja_memory_probe",
                    os.path.join(os.path.dirname(here), "deja-memory", "__init__.py"),
                )
                mod = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(mod)
            except Exception:
                return False
            return True
        try:
            return load_memory_provider("deja-memory") is not None
        except Exception:
            return False
    except Exception:
        return False


def recall(session_id=None, user_message=None, is_first_turn=False, **kwargs):
    # First turn gets the session digest, ranked by the project; every turn
    # after gets the relevance pass over what was just asked. Silence is the
    # normal answer — a hook that talks every turn is wallpaper.
    if _provider_active():
        return None
    if is_first_turn:
        digest = _deja(["hook-context", "--plain"])
        if digest:
            return {"context": digest}
    if not user_message:
        return None
    payload = json.dumps({"prompt": user_message, "session_id": session_id or ""})
    hit = _deja(["hook-prompt", "--plain"], payload)
    return {"context": hit} if hit else None


def search(raw_args):
    """/deja <query> — search past sessions without waiting for a recall."""
    query = (raw_args or "").strip()
    if not query:
        return "Usage: /deja <what you are looking for>"
    # A hook must not stall a turn, but a command the user just typed can
    # wait: a first search may rebuild the index, which took 18s here.
    #
    # "--" when the query names one of deja's own flags: searching for
    # "--json" or "--all-matches" otherwise dies in flag parsing and comes back
    # as an empty history.
    args = ["search", "--", query] if query.startswith("-") else ["search", query]
    found = _deja(args, timeout=120)
    return found or f"Nothing in your history matches {query!r}."


def register(ctx):
    ctx.register_hook("pre_llm_call", recall)
    # Hermes surfaces registered commands in every session and gateway, which
    # is the cheapest way to be found by someone who has not read the docs.
    ctx.register_command(
        "deja",
        handler=search,
        description="Search your own past coding sessions",
    )
`, pyQuote(exe))
}

// pyQuote renders a Python string literal. A Windows path or one with a quote
// in it would otherwise produce a plugin that fails to import.
func pyQuote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}

// yamlQuote renders a YAML double-quoted scalar. An unquoted exe path breaks the
// file the moment it holds a YAML metacharacter — a ": " reads as a nested key,
// a " #" starts a comment, a Windows "C:\..." is at least fragile — and the
// harness then cannot parse its own config. Double-quoting escapes only \ and ",
// which is all a double-quoted scalar needs.
func yamlQuote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}

// installHermesMCP edits config.yaml by hand rather than through a YAML
// round-trip: the file ships with section comments a re-serialise would drop,
// and `hermes mcp add` prompts before saving, which an installer cannot answer.
func installHermesMCP(exe string, uninstall bool) (installResult, error) {
	path := filepath.Join(sources.HermesHome(), "config.yaml")
	old, err := readConfig(path)
	if err != nil {
		return installResult{}, err
	}
	next := removeHermesMCPBlock(lfText(old))
	if !uninstall {
		pad, ok := hermesBlockIndent(next)
		if !ok {
			pad = "  "
		}
		entry := pad + "deja:\n" + pad + pad + "command: " + yamlQuote(exe) + "\n" +
			pad + pad + "args:\n" + pad + pad + pad + "- mcp\n" + pad + pad + "enabled: true\n"
		if i := strings.Index(next, "\nmcp_servers:\n"); i >= 0 {
			at := i + len("\nmcp_servers:\n")
			next = next[:at] + entry + next[at:]
		} else {
			if next != "" && !strings.HasSuffix(next, "\n") {
				next += "\n"
			}
			next += "\nmcp_servers:\n" + entry
			noteBlockAdded(path, "mcp_servers")
		}
	} else if blockWasAdded(path, "mcp_servers") {
		// The container goes with the entry when deja is what put it there —
		// a config the reader owned came back carrying an `mcp_servers:` they
		// never wrote (#2606, the shape #2604 fixed for the JSON writers). One
		// they wrote stays, with or without entries under it.
		if trimmed := dropEmptyYAMLKey(next, "mcp_servers:"); trimmed != next {
			next = trimmed
			forgetBlockAdded(path, "mcp_servers")
		}
	}
	// The file's own final newline, the way both goose writers keep it: this
	// was the only writer that did not, so a config whose deja block ended it
	// came back without one (#2606, #2730).
	a, werr := writeIfChanged(path, old, []byte(keepTrailingNewline(lfText(old), next)))
	return installResult{Path: path, Action: a}, werr
}

// removeHermesMCPBlock drops our entry and nothing else: the block ends at the
// next line that is not more indented, so a neighbouring server survives.
func removeHermesMCPBlock(s string) string {
	lines := strings.Split(s, "\n")
	var out []string
	// Inside `mcp_servers:` and at its own child indent — nothing else. Reading
	// `deja:` at any depth emptied a server of somebody else's whose env holds
	// a key by that name, which is a config deja broke while claiming to
	// uninstall itself (#2730).
	inBlock := false
	child := -1
	for i := 0; i < len(lines); i++ {
		line := lines[i]
		if strings.TrimSpace(line) == "mcp_servers:" && yamlIndentWidth(line) == 0 {
			inBlock, child = true, -1
			out = append(out, line)
			continue
		}
		if inBlock && strings.TrimSpace(line) != "" && yamlIndentWidth(line) == 0 {
			inBlock, child = false, -1
		}
		if inBlock && child < 0 && strings.TrimSpace(line) != "" {
			child = yamlIndentWidth(line)
		}
		if !inBlock || strings.TrimSpace(line) != "deja:" || yamlIndentWidth(line) != child {
			out = append(out, line)
			continue
		}
		pad := yamlIndentWidth(line)
		i++
		for i < len(lines) {
			if strings.TrimSpace(lines[i]) == "" {
				// A blank line is inside the block only if the block goes on
				// after it. The one that separates deja's block from what
				// follows belongs to the file, and eating it made a second
				// install differ from the first.
				j := i
				for j < len(lines) && strings.TrimSpace(lines[j]) == "" {
					j++
				}
				if j < len(lines) && yamlIndentWidth(lines[j]) > pad {
					i = j
					continue
				}
				break
			}
			if yamlIndentWidth(lines[i]) <= pad {
				break
			}
			i++
		}
		i--
	}
	return strings.Join(out, "\n")
}

// hermesBlockIndent is the indent the servers under `mcp_servers:` are written
// at, and whether there is a block to read one from. deja wrote its own entry
// at two whatever the file used, so on a config indented at three or four the
// entry landed shallower than its siblings — and the uninstall that reads
// "indented further than deja's key" then took those siblings with it (#2730).
func hermesBlockIndent(s string) (string, bool) {
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		if strings.TrimSpace(line) != "mcp_servers:" || yamlIndentWidth(line) != 0 {
			continue
		}
		for _, next := range lines[i+1:] {
			if strings.TrimSpace(next) == "" {
				continue
			}
			if yamlIndentWidth(next) == 0 {
				return "", false
			}
			return next[:len(next)-len(strings.TrimLeft(next, " \t"))], true
		}
		return "", false
	}
	return "", false
}

// setHermesPluginEnabled adds or removes deja from plugins.enabled, touching
// only that one list entry so the rest of the file — comments included —
// stays byte-identical.
func setHermesPluginEnabled(on bool) error {
	path := filepath.Join(sources.HermesHome(), "config.yaml")
	if _, err := os.Stat(path); os.IsNotExist(err) && !on {
		return nil
	}
	// readConfig, for the byte order mark: read with it, a `plugins:` on the
	// first line was not found and a second block was appended after it.
	old, err := readConfig(path)
	if err != nil {
		return err
	}
	s := lfText(old)
	blockAdded := blockWasAdded(path, "plugins")
	next, how := editHermesPluginsEnabled(s, on, blockAdded || blockWasAdded(path, "plugins.enabled"), blockAdded)
	switch {
	case how == hermesPluginsUnreadable && on:
		return fmt.Errorf("%s: plugins.enabled is not a list deja can edit; add deja to it by hand", path)
	case how == hermesPluginsUnreadable, !on && how == hermesPluginsMissing, next == s && how != hermesPluginsMissing:
		return nil
	case !on:
		s = next
		forgetBlockAdded(path, "plugins.enabled")
		forgetBlockAdded(path, "plugins")
	case how == hermesPluginsMissing:
		if s != "" && !strings.HasSuffix(s, "\n") {
			s += "\n"
		}
		s += "\nplugins:\n  enabled:\n    - deja\n"
		noteBlockAdded(path, "plugins")
	default:
		s = next
		if how == hermesPluginsKeyAdded {
			noteBlockAdded(path, "plugins.enabled")
		}
	}
	_, err = writeIfChanged(path, old, []byte(s))
	return err
}

const (
	hermesPluginsEdited = iota
	hermesPluginsMissing
	hermesPluginsKeyAdded
	hermesPluginsUnreadable
)

// editHermesPluginsEnabled puts deja into plugins.enabled, or takes it out,
// in whichever style the list is written. Matching only the block form sent a
// flow list — `enabled: [spotify]`, which Hermes' own docs use — to the branch
// that appends a whole second `plugins:`, and YAML keeps the last key, so the
// user's plugins went off (#4243). An `enabled: []` was rewritten as a block
// key, which uninstall then left as null (#4249). A flow list stays a flow
// list, and taking deja out gives back the bytes that were there.
//
// keyAdded says deja wrote the `enabled:` key itself and takes it away with
// its last entry; blockAdded, that it wrote the whole `plugins:` block, which
// goes too once nothing else is in it. Taking the block back whole whatever
// the reader had added to it since hung their `- spotify` off the line above,
// or left their `disabled:` under no parent at all.
//
// A shape deja cannot list itself under is refused rather than guessed at: a
// mapping or a scalar under `enabled:`, a flow list over several lines, and a
// second top-level `plugins:` — Hermes reads the last one.
func editHermesPluginsEnabled(s string, on, keyAdded, blockAdded bool) (string, int) {
	lines := strings.Split(s, "\n")
	p := -1
	for i, line := range lines {
		v, ok := hermesYAMLKey(line, "plugins")
		if !ok || yamlIndentWidth(line) != 0 {
			continue
		}
		if v != "" || p >= 0 {
			return s, hermesPluginsUnreadable
		}
		p = i
	}
	if p < 0 {
		return s, hermesPluginsMissing
	}
	end := len(lines)
	child := ""
	for i := p + 1; i < len(lines); i++ {
		t := strings.TrimSpace(lines[i])
		if t == "" || strings.HasPrefix(t, "#") {
			continue
		}
		if yamlIndentWidth(lines[i]) == 0 {
			end = i
			break
		}
		if child == "" {
			child = lines[i][:yamlIndentWidth(lines[i])]
		}
	}
	if child == "" {
		child = "  "
	}
	k := -1
	val := ""
	for i := p + 1; i < end; i++ {
		if v, ok := hermesYAMLKey(lines[i], "enabled"); ok && lines[i][:yamlIndentWidth(lines[i])] == child {
			if k >= 0 {
				return s, hermesPluginsUnreadable
			}
			k, val = i, v
		}
	}
	if k < 0 {
		if !on {
			return s, hermesPluginsEdited
		}
		lines = slices.Insert(lines, p+1, child+"enabled:", child+child+"- deja")
		return strings.Join(lines, "\n"), hermesPluginsKeyAdded
	}
	switch strings.ToLower(val) {
	case "", "null", "~":
	default:
		return editHermesFlowList(s, lines, k, val, on)
	}
	last, mine, others := k, -1, 0
	for i := k + 1; i < end; i++ {
		t := strings.TrimSpace(lines[i])
		if t == "" || strings.HasPrefix(t, "#") {
			continue
		}
		w := yamlIndentWidth(lines[i])
		if w < len(child) || w == len(child) && !strings.HasPrefix(t, "-") {
			break
		}
		if !strings.HasPrefix(t, "- ") && t != "-" {
			// A mapping or a scalar under the key, or an item running on
			// past its line: nothing a `- deja` can be put beside.
			return s, hermesPluginsUnreadable
		}
		last = i
		if hermesYAMLScalar(strings.TrimPrefix(t, "-")) == "deja" {
			mine = i
		} else {
			others++
		}
	}
	if val != "" && others > 0 {
		return s, hermesPluginsUnreadable
	}
	switch {
	case on && mine >= 0, !on && mine < 0:
		return s, hermesPluginsEdited
	case on:
		if val != "" {
			// `null` and `~` are the empty value a bare key is; the key
			// takes the list the same way and keeps its comment.
			t := strings.TrimLeft(lines[k], " \t")
			rest := t[len("enabled:"):]
			rest = rest[strings.Index(rest, val[:1])+len(val):]
			lines[k] = child + "enabled:" + rest
		}
		indent := child + child
		if last != k {
			indent = lines[last][:yamlIndentWidth(lines[last])]
		}
		lines = slices.Insert(lines, last+1, indent+"- deja")
	case others > 0 || !keyAdded:
		lines = slices.Delete(lines, mine, mine+1)
	case blockAdded && hermesBlockHoldsOnly(lines, p, end, k, mine):
		from := p
		if from > 0 && strings.TrimSpace(lines[from-1]) == "" {
			from--
		}
		lines = slices.Delete(lines, from, mine+1)
	default:
		lines = slices.Delete(lines, mine, mine+1)
		lines = slices.Delete(lines, k, k+1)
	}
	return strings.Join(lines, "\n"), hermesPluginsEdited
}

// hermesBlockHoldsOnly reports whether the plugins block from p to end has
// nothing in it but the `enabled:` key at k and deja's entry at mine — the
// block exactly as deja wrote it.
func hermesBlockHoldsOnly(lines []string, p, end, k, mine int) bool {
	for i := p + 1; i < end; i++ {
		if i != k && i != mine && strings.TrimSpace(lines[i]) != "" {
			return false
		}
	}
	return mine == k+1
}

// editHermesFlowList does the edit on a flow list, `enabled: [a, b]`, inside
// its own brackets: deja goes in after the last item, and taking it out takes
// the comma and space that came with it, so `[ spotify ]` comes back as it
// was. The brackets and commas are found outside quotes, so an item like
// 'x]y' does not end the list.
func editHermesFlowList(s string, lines []string, k int, val string, on bool) (string, int) {
	if items, flow := yamlFlowItems(val); !flow || items == nil {
		return s, hermesPluginsUnreadable
	}
	line := lines[k]
	open := strings.Index(line, "[")
	// The items as spans of the line, each without the space around it.
	type span struct{ from, to int }
	var items []span
	shut, from, quote := -1, open+1, byte(0)
	add := func(to int) {
		f, t := from, to
		for f < t && (line[f] == ' ' || line[f] == '\t') {
			f++
		}
		for t > f && (line[t-1] == ' ' || line[t-1] == '\t') {
			t--
		}
		if f < t {
			items = append(items, span{f, t})
		}
	}
	for i := open + 1; i < len(line) && shut < 0; i++ {
		switch c := line[i]; {
		case quote != 0:
			if c == quote {
				quote = 0
			}
		case c == '\'' || c == '"':
			quote = c
		case c == ',':
			add(i)
			from = i + 1
		case c == ']':
			add(i)
			shut = i
		}
	}
	if shut < 0 {
		return s, hermesPluginsUnreadable
	}
	mine := slices.IndexFunc(items, func(sp span) bool { return hermesYAMLScalar(line[sp.from:sp.to]) == "deja" })
	switch {
	case on && mine >= 0, !on && mine < 0:
		return s, hermesPluginsEdited
	case on && len(items) == 0:
		lines[k] = line[:shut] + "deja" + line[shut:]
	case on:
		at := items[len(items)-1].to
		lines[k] = line[:at] + ", deja" + line[at:]
	case len(items) == 1:
		lines[k] = line[:items[0].from] + line[items[0].to:]
	case mine == 0:
		lines[k] = line[:items[0].from] + line[items[1].from:]
	default:
		lines[k] = line[:items[mine-1].to] + line[items[mine].to:]
	}
	return strings.Join(lines, "\n"), hermesPluginsEdited
}

// hermesYAMLKey reads `key: value` off a line, the value without a trailing
// comment.
func hermesYAMLKey(line, key string) (string, bool) {
	t := strings.TrimLeft(line, " \t")
	if !strings.HasPrefix(t, key+":") {
		return "", false
	}
	rest := t[len(key)+1:]
	if rest != "" && rest[0] != ' ' && rest[0] != '\t' {
		return "", false
	}
	if i := strings.Index(rest, " #"); i >= 0 {
		rest = rest[:i]
	}
	return strings.TrimSpace(rest), true
}

// hermesYAMLScalar is a list item as a name: no comment, no quotes.
func hermesYAMLScalar(v string) string {
	if i := strings.Index(v, " #"); i >= 0 {
		v = v[:i]
	}
	return strings.Trim(strings.TrimSpace(v), `"'`)
}
